config/routes.rb
Rails.application.routes.draw do
  

  root :to => 'languages#content'

  devise_for :users
	resources :languages do
		resources :projects
  	end
  	resources :blogs, only: [:index, :show] do
  		resources :comments, only: [:index, :show, :edit]
  	end	

    resources :references

    resources :users
    resources :feedbacks

   

  	namespace :admin do
  		resources :blogs do
        resources :comments
      end
  	end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :comments
	validates :name, :presence => true
end	

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog 

	validates :description, :presence => true
end	

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :projects
	validates :name, :presence => true
end	

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :language

	validates :description, :presence =>true

end	

app/models/reference.rb
class Reference < ActiveRecord::Base
	validates :name, :presence => true
	validates :content, :presence => true
end	

app/models/user.rb
class User < ApplicationRecord
	has_many :feedbacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < AdminController
	before_action :find_blog, only: [:show, :edit, :update, :destroy]

	def index
		@blogs = Blog.all
	end
	
	def show; end

	def new
		@blog = Blog.new
	end
	
	def create
		@blog = Blog.new(blog_params)

		if @blog.save
			redirect_to blog_path(@blog)
		else
			render :new, alert:"Something went wrong."
		end
	end

	def edit; end

	def update
		if @blog.update(blog_params)	
			redirect_to admin_blog_path(@blog)
		else
			render :edit, alert: "Something went wrong."
		end
	end	

	def destroy
		@blog.destroy
		redirect_to blogs_path, alert: "Successfully deleted publication."			
	end
	
	private

	def find_blog
		@blog = Blog.find(params[:id])
	end
	
	def blog_params
		params.require(:blog).permit(:name, :content)		
	end
end		

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_for_admin
	def check_for_admin
		if current_user.nil? || !current_user.is_admin
			redirect_to root_path, alert: "You must be an admin to access this path."
		end
	end
end		

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def new
		@blog = Blog.new
		render :new
	end

	def index
		@blogs = Blog.all
		render :index
	end

	def show
		@blog = Blog.find(params[:id])
		render :show
	end

	def create
		@blog = Blog.new(blog_params)
		if @blog.save
			redirect_to blogs_path
		else
			render :new
		end
	end

	def edit
		@blog = Blog.find(params[:id])
		render :edit
	end
	
	def update
		@blog = Blog.find(params[:id])
		if @blog.update(blog_params)
			redirect_to blogs_path
		else
			render :edit
		end
	end	

	def destroy	
		@blog = Blog.find(params[:id])
		@blog.destroy
		flash[:notice] = "Blog successful deleted!"
		redirect_to blogs_path
	end			

	private
		def blog_params
			params.require(:blog).permit(:name, :content)	
		end			
end		

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
      @blog = Blog.find(params[:blog_id])
      @comment = @blog.comments.new
    end

    def create
    	@blog = Blog.find(params[:blog_id])
    	@comment = @blog.comments.new(comment_params)

    	if @comment.save
    		redirect_to blogs_path(@comment.blog)
    	else
    		render :new
    	end
    end


    def edit
        @blog = Blog.find(params[:blog_id])
        @comment = @blig.comments.edit(comment_params)
        
    end
    
    
    private
    def comment_params
    	params.require(:comment).permit(:description)			
    end

end

app/controllers/feedback.controller.rb
class FeedbacksController < ApplicationController
  before_action :set_user
  def index
  end

  def edit
  end

  def create
    @user = current_user
    @feedback = @user.feedbacks.new(feedback_params)
    if @feedback.save
      redirect_to root_path, notice: "success"
    else
      redirect_to root_path, alert: "failed"
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :body, :rating)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	before_action :set_user
  def index
  end

  def edit
  end

  def new
  end	

  def create
    @user = current_user
    @feedback = @user.feedbacks.new(feedback_params)
    if @feedback.save
      redirect_to root_path, notice: "success"
    else
      redirect_to root_path, alert: "failed"
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :body)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
	before_action :set_user
	def new
		@language = Language.new
		render :new
	end

	def content 
		@feedbacks=Feedback.all
	end

	def index
		@languages = Language.all
		render :index
	end

	def show
		@language = Language.find(params[:id])
		render :show
	end

	def create
		@language = Language.new(language_params)
		if @language.save
			redirect_to languages_path
		else
			render :new
		end
	end

	def edit
		@language = Language.find(params[:id])
		render :edit
	end
	
	def update
		@language = Language.find(params[:id])
		if @language.update(language_params)
			redirect_to languages_path
		else
			render :edit
		end
	end				

	private
	  def set_user
    	@user = current_user
  	  end
		def language_params
			params.require(:language).permit(:name)	
		end	


end		

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@language = Language.find(params[:language_id])
		@project = @language.projects.new
	end

	def create
		@language = Language.find(params[:language_id])
		@project = @language.projects.new(project_params)
		if @project.save
			redirect_to language_path(@project.language)
		else
			render :new
		end
	end	

	def edit
   		@language = Language.find(params[:language_id])
   		@project = @language.projects.find(params[:id])
   
 	end

	def update
  		 @language = Language.find(params[:language_id])
  		 @project = @language.projects.find(params[:id])
   	if @project.update(project_params)
     	flash[:notice] = "Project successfully updated!"
    	redirect_to language_path(@language)
    else
     	render :edit
   	end
 end

	def destroy
   		@language = Language.find(params[:language_id])
  		@project = @language.projects.find(params[:id])
  		@project.destroy
   		flash[:notice] = "Project successfully deleted!"
   		redirect_to language_path(@language)
 	end

	private
    	def project_params
      		params.require(:project).permit(:description)
    	end
  		
end		

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  def new
    @reference = Reference.new
  end

  def index
    @references = Reference.all
  end

  def show
    @reference = Reference.find(params[:id])
  end

  def create
    @reference = Reference.new(reference_params)
    if @reference.save
      redirect_to references_path
    else
      
    end
  end

  def edit
    @reference = Reference.find(params[:id])
  end

  def update
    @reference = Reference.find(params[:id])
    if @reference.update(reference_params)
      redirect_to references_path
    else
      render :edit
    end
  end

  private
  def reference_params
    params.require(:reference).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/admin/blogs/edit.html.erb
<h1>Edit Blog</h1>

	<% if @blog.errors.any? %>
		<h3>Please fix these errors</h3>
		<ul>
			<% @blog.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<%= form_for @blog, url: admin_blog_path(@blog) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<br>

		<%= f.label :content %>
		<%= f.text_area :content %>

		<br>

		<%= f.submit  %>
		
	<% end %>			

app/views/admin/blogs/new.html.erb
<h1> New Blog </h1>


	<% if @blog.errors.any? %>
		<h3> Oops an error occured. Please try again:</h3>
		<ul>
			<% @blog.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>		


	<%= form_for @blog, url: admin_blogs_path(@blog) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<br>

		<%= f.label :content %>
		<%= f.text_area :content %>
		
		<%= f.submit  %>
		
	<% end %>

app/views/admin/blogs/show.html.erb
<h1><%= @blog.name %></h1>
  <p><%= @blog.content %></p>

<% if current_user && current_user.is_admin? %>
 	<p><%= link_to "Edit blog", edit_admin_blog_path %></p>
  	<p><%= link_to "Delete blog", admin_blog_path(@blog), method: :delete,
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>
<% end %>

	<p><%= link_to "Return to Blogs", blogs_path %></p>S

app/views/admin/comments/new.html.erb
new.html.erb

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

	<% if @blog.errors.any? %>
		<h3>Please fix these errors</h3>
		<ul>
			<% @blog.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<%= form_for @blog do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<br>

		<%= f.label :content %>
		<%= f.text_area :content %>

		<br>

		<%= f.submit  %>
		
	<% end %>			

app/views/blogs/index.html.erb
<div class="container">

<h1> Blog Posts </h1>

	<hr />

</div>
<ul>
	<% @blogs.each do |blog| %>
		<li><%= link_to blog.name, blog_path(blog) %></li>
	<% end %>
</ul>	

<hr>

<% if current_user && current_user.is_admin? %>
	<%= link_to "New blog", new_admin_blog_path %>
<% end %>	

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>
  <p><%= @blog.content %></p>

  <% if @blog.comments.any? %>
  	<h4>View Comments for this post</h4>

  		<ul> 
  			<%  @blog.comments.each do |comment| %>
  				<li>
  					<%= comment.description %> 
  					
                </li>
                <% if current_user && current_user.is_admin? %>
                <%= link_to "Edit", edit_blog_comment_path(@blog, comment) %> 

  				      <%= link_to "Delete", blog_comment_path(@blog, comment), method: :delete, :data => {:confirm => "Are you sure?",
                                                 :method => "delete"} %>
                <% end %>

     		<% end %>
    	</ul>
  <% else %>
    <p>There are no comments yet! Add your own Here <%= link_to "Add a comment", new_blog_comment_path(@blog) %></p>
  <% end %>
                                  

<% if current_user && current_user.is_admin? %>
 	<p><%= link_to "Edit blog", edit_admin_blog_path %></p>
  	<p><%= link_to "Delete blog", admin_blog_path(@blog), method: :delete,
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>
<% end %>

<p><%= link_to "Return to Blogs", blogs_path %></p>

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

  <%= form_for [@blog, @comment] do |f| %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <p><%= f.submit %></p>
  <% end %>
  

app/views/comments/edit.html.erb
<h1>Edit Comment </h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>New Comment for <%= @blog.name %></h1>

<%= render 'form' %>

app/views/comments/show.html.erb
show.html.erb

app/views/feedbacks/edit.html.erb
<h1>Feedbacks#edit</h1>
<p>Find me in app/views/feedbacks/edit.html.erb</p>

app/views/feedbacks/index.html.erb
<h1>Feedbacks#index</h1>
<p>Find me in app/views/feedbacks/index.html.erb</p>

app/views/languages/content.html.erb
<div class="wrapper">
  <header role="header">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse" role="button">
            <span class="sr-only">Toggle Navigation</span>
            
            <span class="icon-bar"></span>
            
            <span class="icon-bar"></span>
            
            <span class="icon-bar"></span>
          </button>

          <a href="#" class="navbar-brand">Isaac N. Onyango</a>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right js-nav">
            <li><a href="home">Home</a></li>
            
            <li><%= link_to "Languages", languages_path %></li>


            <li><%= link_to "Blog", blogs_path %></li>
            
             
             


            <% if user_signed_in? %>
              <li><%= link_to "Sign-Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign-In", new_user_session_path,method: :get %></li>
            <% end %>  

            <li><%= link_to "Reference", references_path %></li 

          </ul>
        </div>
      </div>
    </nav>
  </header>

  <section id="home" class="sec-main">
    <h1 class="main-heading">Where creativity happens.</h1>
  </section>

  <section id="about" class="sec-about">
    <div class="container">

      <h1>About me</h1>

      <hr />

      
      <%= image_tag  "iyke.jpg",  alt:'ontiri', style:"width:200px; height:200px;",  class:"img-circle" %>

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <p>Hi, my name is Isaac Nderi Onyango and I am a Full Stack Web Developer based in Nairobi. I love creating beautiful and responsive web programs in HTML5, JavaScript or Ruby on Rails. My other skills include WordPress and Photoshop. 
            If you want to hire me or just to talk, <a class="js-connect" href="#footer">connect</a> with me.</p>
        </div>
      </div>
    </div>
  </section>
  <section id="services" class="sec-services">
    <div class="container">
      <h1>Services</h1>

      <hr />

      <div class="row">
        <div class="col-sm-4">
          <i class="fa fa-4x fa-file"></i>

          <h2 class="h3">Beautiful Design</h2>

          <p>Every website is beautiful, unique and tailored to suit your needs and requirements.</p>
        </div>

        <div class="col-sm-4">
          <i class="fa fa-4x fa-code"></i>

          <h2 class="h3">Clean Code</h2>

          <p>All websites are written in valid and clean code.</p>
        </div>

        <div class="col-sm-4">
          <i class="fa fa-4x fa-tablet"></i>

          <h2 class="h3">Always Responsive</h2>

          <p>All websites are responsive. They will look great on desktop, tablets and mobile phones too.</p>
        </div>
      </div>
    </div>
  </section>
<section id="testimonials" class="sec-testimonials">
  <div class="container">
  <h1> Testimonials</h1>

    <hr />

    

  <%if user_signed_in?%>
  <div class="feeback form">
  <%= form_for :feedback, url: feedbacks_path(current_user) do |f|%>
    <div class="form-group">
      <%= f.text_field :name,  required: true%>
    </div>
    <div class="form-group">
      <%= f.text_area :body, required: true%>
    </div>
    <div class="form-group">
      <%= f.button "submit"%>
    </div>
    <%end%>
</div>
  <%else%>

  <h5> Please Sign In to leave a Testimonial</h5>
<%end%>
<div>
  <%@feedbacks.each do |feedback|%>
      <h1><%= feedback.name%></h1>
        <p><%= feedback.body%></p>
  <%end%>
</div>
</div>
</section>
  <section id="contact" class="sec-contact">
    <div class="container">
      <h1>Contact Me</h1>

      <hr />

      <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
        <form method="post" action="mailto:nderiony95@youremail.com" >
          <form class="center-block" action="#" method="post">
            <div class="form-group">
              <label class="sr-only" for="inputName">Full name</label>

              <input id="inputName" class="form-control" type="text" placeholder="Name" required />
            </div>

            <div class="form-group">
              <label for="inputMail" class="sr-only">Email Address</label>

              <input id="inputMail" class="form-control" type="email" placeholder="email" required />
            </div>

            <div class="form-group">
              <label for="inputMessage" class="sr-only">Your Message</label>

              <textarea id="inputMessage" class="form-control" name="message" cols="30" rows="8" required></textarea>
            </div>

            <div class="form-group">
              <button class="btn btn-default center-block" type="submit" value="Hire me">Contact Me</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

  <footer id="footer">
    <div class="container">
      <ul class="soc-media-ul">
        <li>
          <a href="https://plus.google.com/u/0/+Nderionyango" class="fa fa-google-plus" target="_blank"></a>
        </li>

        <li>
          <a href="https://www.facebook.com/IsaacNderi" class="fa fa-facebook" target="_blank"></a>
        </li>

        <li>
          <a href="mailto:nderiony95@gmail.com" class="fa fa-envelope"></a>
        </li>
      </ul>
    </div>
  </footer>
</div>

app/views/languages/edit.html.erb
<h1>Edit Language</h1>

	<% if @language.errors.any? %>
		<h3>Please fix these errors</h3>
		<ul>
			<% @language.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<%= form_for @language do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.submit  %>
		
	<% end %>			

app/views/languages/index.html.erb
<div class="container">
	<h1> Languages Proficient </h1>
	<hr />
</div>


<ul>
	<% @languages.each do |language| %>
		<li><%= link_to language.name, language_path(language) %></li>
	<% end %>
</ul>	

<hr>
<% if current_user && current_user.is_admin? %>
	<%= link_to "New language", new_language_path %>
<% end %>  

app/views/languages/new.html.erb
 <h1> New Language </h1>

<%= form_for @language do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.submit  %>
		
	<% end %>			

app/views/languages/show.html.erb
<h1><%= @language.name %></h1>

 <% if @language.projects.any? %>
    <h4>Here are the projects for this language:</h4>

    <ul>
      <% @language.projects.each do |project| %>
        <li>
          <%= project.description %> 
          <% if current_user && current_user.is_admin? %>
            <%= link_to "Edit", edit_language_project_path(@language, project) %> |
            <%= link_to "Delete", language_project_path(@language, project),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
          <% end %>                                        
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no projects yet!</p>
  <% end %>
<% if current_user && current_user.is_admin? %>
  <p><%= link_to "Add a project", new_language_project_path(@language) %></p>
  <p><%= link_to "Delete language", language_path(@language),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>
<% end %>   

	<p><%= link_to "Return to Languages", languages_path %></p>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Personal Portfolio</title>
    <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
    <%= yield %>
    
    
  </body>
</html>

app/views/projects/_form.html.erb
<%= render('layouts/errors', :object => @projects) %>

  <%= form_for [@language, @project] do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <p><%= f.submit %></p>
  <% end %>
  

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

  <%= render 'form' %>
  

app/views/projects/new.html.erb
<h1>New project for <%= @language.name %></h1>

  <%= render 'form' %>
  

app/views/references/index.html.erb
<div class="container">
<h1> Here are my Referees </h1>

<hr />
</div>


<ul>
	<%@references.each do |reference|%>
		<li><%= reference.name %></li>
	<% end %>
</ul>		

<% if current_user && current_user.is_admin? %>
	<%= link_to "New reference", new_reference_path %>
<% end %>  

app/views/references/new.html.erb
<h1>New referees</h1>

<%= form_for @reference do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>

		<hr />
		<%= f.label :content %>
		<%= f.text_area :name %>
		<%= f.submit  %>
		
	<% end %>			

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>